### PR TITLE
java example using jsonpath, grizzly and capsule dockerised for in container maven builds 

### PR DESCRIPTION
**Pull request by sfkamath**
java implemententation using grizzly and jsonpath

### CODE REVIEW

**Comment by willp-bl** [comment]
Please rebase this on master and use the new docker/test script format, plus use a more descriptive commit message :)

**Comment by sfkamath** [comment]
About the docker test script - are you referring to the one in the nancy folder?

**Comment by willp-bl** [comment]
Yes, probably easiest to reuse one of the test.sh scripts and an appropriate Dockerfile

**Comment by sfkamath** [comment]
done

**Pull request merged**
