### PR TITLE
Initial clojure implementation using yada

### PR DESCRIPTION
**Pull request by kornysietsma**
Note I didn't include it in the main pre-commit script, wasn't sure about convincing Travis to run it.

### CODE REVIEW

**Comment by willp-bl** [comment]
Please rebase this on master and use the new docker/test script format

**Comment by kornysietsma** [comment]
updated to use Docker, added to main precommit.sh as well.  Note that I still have to wait for the server to be fully started in the test script - not sure why other versions aren't having this problem, maybe it's just they don't have the wonderful slow start time of clojure!

**Comment by willp-bl** [comment]
Could do this: https://github.com/alphagov/verify-sample-local-matching-services/blob/master/test_csharp.sh#L21

**Comment by kornysietsma** [comment]
I saw the C# one - I feel happier waiting for the healthcheck url to work, somehow that feels cleaner than looking for log messages.  I tried using a Docker HEALTHCHECK command, but it was giving me headaches so I went back to using curl in a loop.

**Comment by willp-bl** [comment]
This has merge conflicts at the moment, and there are a lot of commits re-written from master - can they be removed?

**Comment by kornysietsma** [comment]
Hmm - I seem to have messed up my github-fu somewhere.  I'll look into it.

**Comment by kornysietsma** [comment]
killing this - new Yada branch has clean PR

**Pull request closed without merging**
